#OneBlock Plugin Configuration file
#by MrMarL & Adarsh A

#Specify the World Name.
world: world
#The Cordinates where the postion of your First OneBlock is set.
x: 0.0
y: 0.0
z: 0.0
#This is the place where a player gets tp-ed when they execute /ob leave
leaveworld: world
#Specify the Lobby World
xleave: 0.0
yleave: 0.0
zleave: 0.0
yawleave: 0.0
#Should we enable the Progress Bar?
progress_bar: true
#What shoud progress bar show?
progress_bar_text: level
#Shoud we enable chat alert for Levels
chat_alert: true
#ProgressBar Color
progress_bar_color: GREEN
#Shoud we Create New Islands for New Players?
island_for_new_players: true
#Should the player get tp-ed to the island again after the death in game?
rebirth_on_the_island: true
#Level Multiplier 
#Default value: 5
level_multiplier: 5
#Should we Prevent other players going from their island to others islands?
protection: false
#Create a WorldGuard region for each island? (only premium)
worldGuard: true
#This is the block-distance between one Island to other.
#Default value 100. If you increase this then More chunks will be generated.
#Which causes more storage to be occupied
set: 100
#Use the island creation mode in a circle?
circleMode: true
#Toss drop(item) up above the block?
droptossup: true
#Apply physics to blocks? //for example: falling gravel
physics: false
#Limits the number of people on the island. (0 - unlimited)
max_players_team: 0
#Keep player inventory after id reset?
saveplayerinventory: false

# OneBlock Configuration

# Radius in blocks for bossbar activation
radius: 10

# Mode: 'scenario' for sequential blocks, 'random' for random blocks
mode: scenario

# Bossbar settings
bossbar:
  enabled: true
  color: BLUE
  style: SOLID

# Stages configuration
stages:
  grass:
    name: "Grass Stage"
    blocks-required: 100
    blocks:
      - GRASS_BLOCK
      - DIRT
      - STONE
    mobs:
      - COW
      - SHEEP
      - CHICKEN
    mob-spawn-chance: 0.1

  stone:
    name: "Stone Stage"
    blocks-required: 150
    blocks:
      - STONE
      - COBBLESTONE
      - GRAVEL
    mobs:
      - ZOMBIE
      - SKELETON
      - SPIDER
    mob-spawn-chance: 0.15

  ore:
    name: "Ore Stage"
    blocks-required: 200
    blocks:
      - COAL_ORE
      - IRON_ORE
      - GOLD_ORE
      - REDSTONE_ORE
      - LAPIS_ORE
      - DIAMOND_ORE
    mobs:
      - CREEPER
      - ENDERMAN
      - WITCH
    mob-spawn-chance: 0.2

  nether:
    name: "Nether Stage"
    blocks-required: 250
    blocks:
      - NETHERRACK
      - SOUL_SAND
      - GLOWSTONE
      - NETHER_BRICKS
    mobs:
      - BLAZE
      - MAGMA_CUBE
      - GHAST
    mob-spawn-chance: 0.25

  end:
    name: "End Stage"
    blocks-required: 300
    blocks:
      - END_STONE
      - PURPUR_BLOCK
      - OBSIDIAN
    mobs:
      - ENDERMAN
      - SHULKER
    mob-spawn-chance: 0.3