name: OneBlock
version: '${project.version}'
main: Oneblock.OneBlockPlugin
api-version: '1.20'
authors: [MrMarL]
description: A plugin that creates a single block that changes as you break it
softdepend: [PlaceholderAPI, CoreProtect]

commands:
  setoneblock:
    description: Set a OneBlock at your location
    usage: /<command>
    permission: oneblock.set
  removeoneblock:
    description: Remove a OneBlock at your location
    usage: /<command>
    permission: oneblock.remove

permissions:
  oneblock.set:
    description: Allows setting OneBlocks
    default: op
  oneblock.remove:
    description: Allows removing OneBlocks
    default: op